/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JTextArea;
import pokemonthegame.*;

public class BattleScreen extends javax.swing.JFrame {

    /**
     * Creates new form BattleScreen
     */
    public BattleScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        GaryButton = new javax.swing.JButton();
        DawnButton = new javax.swing.JButton();
        BrockButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Frame1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jFrame2.setMinimumSize(new java.awt.Dimension(500, 500));
        jFrame2.setSize(new java.awt.Dimension(500, 500));

        jLabel2.setText("Frame2");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel2)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 560));
        setPreferredSize(new java.awt.Dimension(900, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newgary.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel5.setMinimumSize(new java.awt.Dimension(250, 250));
        jLabel5.setPreferredSize(new java.awt.Dimension(250, 250));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, 210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newdawn.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ddzjhi2-e9c602fc-aa4b-4f29-871d-b2ff2348300e.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        jLabel8.setText("Choose your opponent:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        GaryButton.setBackground(new java.awt.Color(51, 153, 255));
        GaryButton.setFont(new java.awt.Font("CC Astro City", 0, 12)); // NOI18N
        GaryButton.setText("Gary");
        GaryButton.setToolTipText("");
        GaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        DawnButton.setBackground(new java.awt.Color(204, 153, 255));
        DawnButton.setFont(new java.awt.Font("CC Astro City", 0, 12)); // NOI18N
        DawnButton.setText("Dawn");
        DawnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DawnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DawnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        BrockButton.setBackground(new java.awt.Color(255, 153, 0));
        BrockButton.setFont(new java.awt.Font("CC Astro City", 0, 12)); // NOI18N
        BrockButton.setText("Brock");
        BrockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrockButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BrockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        jLabel3.setToolTipText("");
        jLabel3.setMinimumSize(new java.awt.Dimension(2560, 942));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 22, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titulogame.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forest-background-5th-style-pass-portfolio-edit.png"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(900, 563));
        jLabel4.setPreferredSize(new java.awt.Dimension(900, 563));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1040, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Esse botão inicia a tela de batalha do Gary
    private void GaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaryButtonActionPerformed
        this.dispose();
        GaryScreen gary = new GaryScreen();
        gary.setVisible(true);
    }//GEN-LAST:event_GaryButtonActionPerformed
    //Esse botão inicia a tela de batalha do Brock
    private void BrockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrockButtonActionPerformed
        this.dispose();
        BrockScreen brock = new BrockScreen();
        brock.setVisible(true);
    }//GEN-LAST:event_BrockButtonActionPerformed
    //Esse botão inicia a tela de batalha da Dawn
    private void DawnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DawnButtonActionPerformed
        this.dispose();
        DawnScreen dawn = new DawnScreen();
        dawn.setVisible(true);
    }//GEN-LAST:event_DawnButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrockButton;
    private javax.swing.JButton DawnButton;
    private javax.swing.JButton GaryButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    
    
    
    
}
