/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import pokemonthegame.*;

/**
 *
 * @author leonh
 */
public class DawnScreen extends javax.swing.JFrame {

    /**
     * Creates new form DawnScreen
     */
    public DawnScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        pikachu = new javax.swing.JLabel();
        feraligtr = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("Move 1");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Move 2");

        jButton3.setText("Move 3");

        jButton4.setText("Move 4");

        logout.setText("Logout");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 450));
        setPreferredSize(new java.awt.Dimension(480, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pikachu-f.png"))); // NOI18N
        pikachu.setToolTipText("");
        getContentPane().add(pikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 60));

        feraligtr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/feraligatr.png"))); // NOI18N
        getContentPane().add(feraligtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jButton5.setText("Move 1");
        jButton5.setToolTipText("");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jButton6.setText("Move 2");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jButton7.setText("Move 3");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jButton8.setText("Move 4");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        logout1.setText("Logout");
        getContentPane().add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aerodactil.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venosaur.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounddawn.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DawnScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DawnScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DawnScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DawnScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DawnScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feraligtr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JLabel pikachu;
    // End of variables declaration//GEN-END:variables

    public void DawnBattleBegins() {
        //TYPES
        pokemonthegame.Type fireType = new pokemonthegame.Type("FOGO");
        pokemonthegame.Type eletricType = new pokemonthegame.Type("ELÉTRICO");
        pokemonthegame.Type waterType = new pokemonthegame.Type("ÁGUA");
        pokemonthegame.Type flyingType = new pokemonthegame.Type("VOADOR");
        pokemonthegame.Type grassType = new pokemonthegame.Type("GRAMA");
//Player
        Trainer player = new Trainer("Red", "Player", 2, 'd');
        
        Move[] MovePkm1 = new Move[4];        
        MovePkm1[0] = new Move("Thunder Wave","um golpe",40, eletricType, 10);
        MovePkm1[1] = new Move("Thunderbolt","um golpe",70, eletricType, 8);
        MovePkm1[2] = new Move("Thunder","um golpe",90, eletricType, 5);
        MovePkm1[3] = new Move("Thunder Shock","um golpe", 100, eletricType, 2);        

        Move[] MovePkm2 = new Move[4];        
        MovePkm2[0] = new Move("Water Jet","um golpe",40, waterType, 10);
        MovePkm2[1] = new Move("Surf","um golpe",60, waterType, 8);
        MovePkm2[2] = new Move("Hydro pump","um golpe",90, waterType, 5);
        MovePkm2[3] = new Move("Waterfall","um golpe",100, waterType, 2);        

        Pokemon[] pkmPrincipal = new Pokemon[2];
        pkmPrincipal[0] = new Pokemon("Pikachu", eletricType, fireType, 50, 200, 80, 50, 90);
        pkmPrincipal[0].setMoves(MovePkm1);
        
        pkmPrincipal[1] = new Pokemon("Feraligatr", waterType, grassType,50, 200, 75, 67, 85);
        pkmPrincipal[1].setMoves(MovePkm2);
        
        player.setPokemon(pkmPrincipal);
        
        
//Gary        
        Trainer opponent1 = new Trainer("Gary", "Opponent", 2, 'd');
        
        Move[] MovePkm3 = new Move[4];        
        MovePkm3[0] = new Move("Air Slash","Um corte de Ar",40, flyingType, 10);
        MovePkm3[1] = new Move("Huricane","Um tornado",60, flyingType, 8);
        MovePkm3[2] = new Move("Gust","um golpe",80, flyingType, 5);
        MovePkm3[3] = new Move("Air Cutter","um golpe", 100, flyingType, 2);        

        Move[] MovePkm4 = new Move[4];        
        MovePkm4[0] = new Move("Lava Fist","um golpe",40, fireType, 10);
        MovePkm4[1] = new Move("Fire Cannon","um golpe",60, fireType, 8);
        MovePkm4[2] = new Move("Incinerate","um golpe",85, fireType, 5);
        MovePkm4[3] = new Move("Fire Explosion","um golpe",100, fireType, 2);        

        Pokemon[] pkmSecondary1 = new Pokemon[2];
        pkmSecondary1[0] = new Pokemon("Pidgeot", flyingType, eletricType, 50, 200, 60, 55, 80);
        pkmSecondary1[0].setMoves(MovePkm3);
        
        pkmSecondary1[1] = new Pokemon("Magmortar", fireType, waterType, 50 , 200, 50, 60, 70);
        pkmSecondary1[1].setMoves(MovePkm4); 
        
        opponent1.setPokemon(pkmSecondary1);
        
//Dawn
        Trainer opponent2 = new Trainer("Dawn", "Opponent", 2, 'd');
        
        Move[] MovePkm5 = new Move[4];        
        MovePkm5[0] = new Move("Whip","um golpe",40, grassType, 10);
        MovePkm5[1] = new Move("Leaf Storm","um golpe",50, grassType, 8);
        MovePkm5[2] = new Move("Seed Gatling","um golpe",70, grassType, 5);
        MovePkm5[3] = new Move("Solar Beam","um golpe", 100, grassType, 2);        

        Move[] MovePkm6 = new Move[4];        
        MovePkm6[0] = new Move("Aerial Ace","um golpe",40, flyingType, 10);
        MovePkm6[1] = new Move("Wing Attack","um golpe",60, flyingType, 8);
        MovePkm6[2] = new Move("Sky Attack","um golpe",90, flyingType, 5);
        MovePkm6[3] = new Move("Sky Drop","um golpe",100, flyingType, 2);        

        Pokemon[] pkmSecondary2 = new Pokemon[2];
        pkmSecondary2[0] = new Pokemon("Venusaur", grassType, fireType, 50, 200, 85, 90, 45);
        pkmSecondary2[0].setMoves(MovePkm5);
        
        pkmSecondary2[1] = new Pokemon("Aerodactyl", flyingType, eletricType,50, 200, 60, 80, 95);
        pkmSecondary2[1].setMoves(MovePkm6);
        
        opponent2.setPokemon(pkmSecondary2);
        
//LIDER GINASIO Brock
        Trainer liderGinasio = new Trainer("Gym Leader Brock", "Leader", 2, 'd');
        
        Move[] MovePkm7 = new Move[4];        
        MovePkm7[0] = new Move("Lava Beam","um golpe",40, fireType, 10);
        MovePkm7[1] = new Move("Fire Fang","um golpe", 70, fireType, 8);
        MovePkm7[2] = new Move("Flame claws","um golpe",90, fireType, 5);
        MovePkm7[3] = new Move("Supernova","um golpe",100, fireType, 2);        

        Move[] MovePkm8 = new Move[4];        
        MovePkm8[0] = new Move("Frenzy Plant","um golpe",40, grassType, 10);
        MovePkm8[1] = new Move("Leaf Storm","um golpe",60, grassType, 8);
        MovePkm8[2] = new Move("Seed Bomb","um golpe",70, grassType, 5);
        MovePkm8[3] = new Move("Giga Drain","um golpe",100, grassType, 2);        

        Pokemon[] pkmLeader = new Pokemon[2];
        pkmLeader[0] = new Pokemon("Entei", fireType, waterType, 75, 200, 70, 45, 80);
        pkmLeader[0].setMoves(MovePkm7);
        
        pkmLeader[1] = new Pokemon("Sceptile", grassType, flyingType, 75, 200, 70, 60, 85);
        pkmLeader[1].setMoves(MovePkm8);
        
        liderGinasio.setPokemon(pkmLeader);
    
// TREINADORES / OPONENTES

        Trainer[] trainers = new Trainer[4];        
        trainers[0] = player;
        trainers[1] = opponent1;
        trainers[2] = opponent2;
        trainers[3] = liderGinasio;        
        Battle battle = new Battle(trainers);
        String opponent;
        String winner;
        int i = 0;
        
        battle.chooseOpponent(2);
        }
}
